"""add created_at to booking

Revision ID: 11fc9138a147
Revises: 77fb596539f2
Create Date: 2025-10-28 23:47:04.899359

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11fc9138a147"
down_revision: Union[str, Sequence[str], None] = "77fb596539f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


# add column without server_default
# op.add_column("bookings", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))

# manually populate with current time
conn = op.get_bind()
conn.execute(sa.text("UPDATE bookings SET created_at = :now"), {"now": datetime.utcnow()})

# then make it non-nullable
with op.batch_alter_table("bookings") as batch_op:
    batch_op.alter_column("created_at", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "created_at")
    # ### end Alembic commands ###
