"""update bookingstatus enum values

Revision ID: 77fb596539f2
Revises: b7d2904fcc2c
Create Date: 2025-10-28 22:57:27.127863

"""

from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77fb596539f2"
down_revision: Union[str, Sequence[str], None] = "b7d2904fcc2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
