"""add category column to ammunition

Revision ID: b7d2904fcc2c
Revises: 371f38995421
Create Date: 2025-10-28 17:51:22.811133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7d2904fcc2c"
down_revision: Union[str, Sequence[str], None] = "371f38995421"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ammunitions", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ammunitions", "category")
    # ### end Alembic commands ###
